### ISSUE TITLE
Tama merge.

### ISSUE THREAD

**Issue by cculma** [GenomeRIK/tama#33] opened 2020-10-05 22:14 UTC
Hi, I have a question: I am merging transcriptomes previously checked in TAMA-Collapse and Sqanti3, from different tissues, treatments and plant varieties to obtain a bid bed file with unique IDs. However, after merging the transcriptomes, the prefix_merge.txt does not contain all my initial transcripts. Is there a way or parameter to obtain the same Isoform number? Thanks in advance.

Best,

Cesar

**Comment by GenomeRIK** [comment] 2020-10-06 16:24
Hi Cesar,

Thank you for using TAMA and bringing up this issue.

I am not sure I completely understand your problem here. 

The prefix_merge.txt file should have this format:
1       219     3261    G1.2;spleen_G1.1        40      +       219     3261    255,0,0 5       98,93,181,107,714       0,1457,1757,2132,2328

So for the 4th column we have:
G1.2;spleen_G1.1 

The first ID is the new merged ID and the second ID is the ID from the pre-merged files with the prefix extension (as defined in the filelist.txt input file).

Could you show me a line from your prefix_merge.txt file?
Could you copy/paste lines from the input bed12 files?

Cheers,
Richard

**Comment by cculma** [comment] 2020-10-06 18:12
Hi Richard, here I explain better my issue: 
I have some bed files: `Sanarac_SS_Root.bed`, `Sanarac_SS_Stem.bed`, `Sanarac_SS_Leaf.bed` ..., when I merge them I get a `fusion_all.bed` with the following dimensions and fields: 

`> dim(fusion_all.bed)`
`[1] 1124275      12`
`> head(fusion_all.bed)`
`10028   3737    9667    G1;G1.1 40      -       3737    9667    0,0,255 4       328,482,366,336 0,441,1286,5594`
`10028   3739    9642    G1;G1.2 40      -       3739    9642    255,200,0       5       326,80,234,366,311      0,439,687,1284,5592`
`10028   3811    9671    G1;G1.3 40      -       3811    9671    200,0,255       4       254,482,366,340 0,367,1212,5520`

Additionally, I get the file `fusion_all_merge.txt` with the following dimensions and fields:
`dim(fusion_all_merge.txt)`
`3408354      12`
`> head(fusion_all_merge.txt)`
`10166   15584   16728   G2.1;Sanarac_SS_Root_G16.6      40      -       15584   16728   255,0,0 1       1144    0`
`10166   15584   16728   G2.1;Sanarac_SS_Stem_G20.18     40      -       15584   16728   255,0,0 1       1144    0`
`10166   15584   16728   G2.1;Sanarac_CK_Stem_G22.22     40      -       15584   16728   255,0,0 1       1144    0`
`10166   15584   16728   G2.1;Sanarac_CK_Leaf_G24.19     40      -       15584   16728   255,0,0 1       1144    0`

I am interested in `fusion_all_merge.txt`. As I understand, in the 4th column the first ID `G2.1` correspond to the new ID (unified among transcriptomes) and the last part `_G16.6` is the old ID. In the middle, it is the treatment. Now, if I subset `fusion_all_merge.txt` by treatment, the isoform number of subset files must be equal to the original bed files, right? However, the isoforms number in subset files is different compared with isoforms number in original bed files.

`Saranac_CK_Root.bed`
`dim`
`164638     12`

subset Saranac_CK_Root from `fusion_all_merge.txt`
`dim`
`170896     12`


Is there a way to obtain the same isoforms number? 

Best,

Cesar

**Comment by cculma** [comment] 2020-10-06 18:13
Hi Richard, here I explain better my issue:
I have some bed files: Sanarac_SS_Root.bed, Sanarac_SS_Stem.bed, Sanarac_SS_Leaf.bed ..., when I merge them I get a fusion_all.bed with the following dimensions and fields:

> dim(fusion_all.bed)
[1] 1124275 12
> head(fusion_all.bed)
10028 3737 9667 G1;G1.1 40 - 3737 9667 0,0,255 4 328,482,366,336 0,441,1286,5594
10028 3739 9642 G1;G1.2 40 - 3739 9642 255,200,0 5 326,80,234,366,311 0,439,687,1284,5592
10028 3811 9671 G1;G1.3 40 - 3811 9671 200,0,255 4 254,482,366,340 0,367,1212,5520

Additionally, I get the file fusion_all_merge.txt with the following dimensions and fields:
dim(fusion_all_merge.txt)
3408354 12
> head(fusion_all_merge.txt)
10166 15584 16728 G2.1;Sanarac_SS_Root_G16.6 40 - 15584 16728 255,0,0 1 1144 0
10166 15584 16728 G2.1;Sanarac_SS_Stem_G20.18 40 - 15584 16728 255,0,0 1 1144 0
10166 15584 16728 G2.1;Sanarac_CK_Stem_G22.22 40 - 15584 16728 255,0,0 1 1144 0
10166 15584 16728 G2.1;Sanarac_CK_Leaf_G24.19 40 - 15584 16728 255,0,0 1 1144 0

I am interested in fusion_all_merge.txt. As I understand, in the 4th column the first ID G2.1 correspond to the new ID (unified among transcriptomes) and the last part _G16.6 is the old ID. In the middle, it is the treatment. Now, if I subset fusion_all_merge.txt by treatment, the isoform number of subset files must be equal to the original bed files, right? However, the isoforms number in subset files is different compared with isoforms number in original bed files.

Saranac_CK_Root.bed
dim
164638 12

subset Saranac_CK_Root from fusion_all_merge.txt
dim
170896 12

Is there a way to obtain the same isoforms number?

Best,

Cesar

**Comment by GenomeRIK** [comment] 2020-10-06 18:38
Hi Cesar,

Ok I think I understand now what is going on. To confirm could you copy/paste the command line you used for running TAMA Merge and the contents of the filelist.txt file?

I suspect that you used the "no_cap" mode for the bed files in the filelist.txt file. If this is the case then 5' shorter transcript models can be matched to multiple 5' longer models depending on the way the models present. This is why you are getting more lines from the "Saranac_CK_Root" subset in the merge file as compared to the original input bed file. 

So if you try this you can see all the input models which are supporting more than 1 merge model:

cat Saranac_CK_Root from fusion_all_merge.txt | grep "Sanarac_SS_Root_" | awk '{print $4} | awk -F ";" '{print $2}' | sort | uniq -c | awk '{if($1>1) print $0}'

If you don't want this behaviour you can run again using "capped" mode for all input bed files. 

But please send the information on the command line and filelist.txt file  and I can double check that this is the problem. 

Cheers,
Richard

**Comment by cculma** [comment] 2020-10-08 11:50
Thank you! I ran Tama merge using capped mode and 2,1,1 options and this produce the same isoform numbers.
I have other question: Is there is a restriction related with memory limit during parsing?

I have the following problem during the parsing:

`Traceback (most recent call last):`
`  File "../../../../Iso_assay/tama/tama/tama_go/orf_nmd_predictions/tama_orf_blastp_parser.py", line 41, in <module>`
`    blastp_file_contents = open(blastp_file).read().rstrip("\n").split("\n")`
`MemoryError`

Best,

Cesar

**Comment by GenomeRIK** [comment] 2020-10-08 14:50
Hi Cesar,

It looks like your new question is referring to the usage of another tool "tama_orf_blastp_parser.py". Are you running the ORF/NMD pipeline? 

If so, then the issue is likely that your input blastp file is too large and you do not have enough memory to process it using "tama_orf_blastp_parser.py". Could you tell me the size of your blastp result file? Could you also share the command line you used to run this?

Cheers,
Richard

**Comment by cculma** [comment] 2020-10-09 00:14
Hi, yes, I am running ORF/NMD pipeline. It is a big file:

`117G Oct  7 13:45 blastp_merge_capped`
Composed of `75215480` sequences producing a file with `2457403379` lines

This is my script:

```
#!/bin/bash
for i in *.bed
do      
        p=${i%%.bed}
        echo ${p};
        UNIREF=/path/to/uniprot/uniref100/uniref100;
        ORF_PARSE=/path/to/tama/tama_go/orf_nmd_predictions/tama_orf_blastp_parser.py;
        ORF_SEEKER=/path/to/tama/tama_go/orf_nmd_predictions/tama_orf_seeker.py
        CDS_BED=/path/to/tama/tama_go/orf_nmd_predictions//tama_cds_regions_bed_add.py;
                bedtools getfasta -name -split -s -fi final.all.fasta -bed ${p}.bed -fo ${p}.fasta;
                python $ORF_SEEKER -f ${p}.fasta -o orf_${p};
                diamond blastp -d $UNIREF -q orf_${p} -o blastp_${p} -f 0 -b6;
                python $ORF_PARSE -b blastp_${p} -o parse_${p};
                python $CDS_BED -p parse_${p} -a ${p}.bed -f ${p}.fasta -o blastp_${p}.bed;
done
```

Thank you!

Cesar

**Comment by GenomeRIK** [comment] 2020-10-10 18:55
Hi Cesar,

Ok I just made an update which should reduce memory usage for that tool. Could you git clone again and try to run "tama_orf_blastp_parser.py" again?

Cheers,
Richard

**Comment by cculma** [comment] 2020-10-12 17:07
Perfect! now it works fine. Thank you for your support.

Cesar

**Comment by GenomeRIK** [comment] 2020-10-12 17:12
Glad to hear it's working well now!
Thanks for using TAMA!

Cheers,
Richard

**Closed by GenomeRIK** 2020-10-12 17:12 UTC
