### ISSUE TITLE
TAMA and cDNA Cupcake

### ISSUE THREAD

**Issue by BeatrizdeToledo** [GenomeRIK/tama#21] opened 2020-03-11 16:41 UTC
Good afternoon,
For my PAC-BIO sequencing I performed the 5' cap selection step, therefore I am currently interested in using the TAMA Collapse.
But I also want to use the SQANTI2 for classification and filtering of the isoforms. https://github.com/Magdoll/SQANTI2
In the SQANTI2, cDNA cupcake is used for collapsing  https://github.com/Magdoll/cDNA_Cupcake/wiki#install 
https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step
However for me is not clear if it supports 5' cap selected libraries. 
Is it more advised to run the SQANTI2 as it is or to use TAMA Collapse and then use the result to run SQANTI2?
Thank you
Beatriz

**Comment by GenomeRIK** [comment] 2020-03-11 18:02
Hi Beatriz,

Thank you for considering TAMA. As far as I am aware, there should be no issue using the TAMA Collapse output with 5' cap libraries and collapsing method with SQANTI2. You will just need to convert the TAMA Collapse output to the right format for running with SQANTI2. 

There is some issue with the TAMA headers not working with SQANTI but I will be releasing a format convertor to take care of this. 

However, if you are in a rush you can tweak the headers yourself with a simple script. 

The issue is that TAMA makes the ID's look like this:
>G1;G1.1::chr1:3199734-3201300
AAAATGACCACAGTGTA

Whereas SQANTI wants them to look like this:
>PB.3.1|chr1:4857776-4897906(+)|i1_c1034/f143p70/2586 
AAAATGACCACAGTGTA

So you just need to remove the Gene ID and use the "|" as delimiters instead of the ":".

I just haven't had the time to build the full convertor yet. If you can wait, just follow this repo and you should be able to see when the convertor as been added.

Cheers,
Richard

**Comment by GenomeRIK** [comment] 2020-04-02 14:30
Hi Beatriz,

Not sure if you found a solution for your problem but it's been a while so I am closing this thread. Feel free to make another thread if you have another issue or comment on this thread if this issue has not been resolved. 

Cheers,
Richard

**Closed by GenomeRIK** 2020-04-02 14:30 UTC
