### ISSUE TITLE
Genome seq error 

### ISSUE THREAD

**Issue by HegedusB** [GenomeRIK/tama#19] opened 2020-02-13 21:10 UTC
Hi Rik,
I have tried out recently tama with 5’-capped ONT reads. The reads were mapped to the reference genome with desalt mapper. When I run the tama_collapse.py script the script started to process the reads but after a short time It gave me this message: Genome seq is not the same length as query seq. Can you help me to figure out what could be the problem?
Thanks for any help!

Used command: python tama/tama_collapse.py -s alignment.bam -b BAM -f ref_genome.fasta -p strain_name -x capped -icm ident_map

**Comment by GenomeRIK** [comment] 2020-02-13 22:29
Hello,

I have not tested TAMA Collapse on desalt outputs so I am not sure if it is a desalt formatting thing. However, this error typically occurs if the genome fasta provided in the input is not the same as the one that was mapped to for the BAM/SAM file. 

The error output you got should have also shown 4 lines following it (genome seq, query seq, genome pos, seq pos). I will need those lines to figure out what is going on. Could you copy paste them here? Or if you feel that it is sensitive, you can email it to me. Without those lines or the BAM and Fasta file there is no way for me to identify the issue. You can find my email on the home page of this repo. 

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-14 06:31
Hi,
Thanks a lot for the quick answer! I copy here the whole error message. 

Genome seq is not the same length as query seq
['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'G', 'C', 'C', 'A', 'A', 'T', 'T', 'T', 'G', 'C', 'G', 'A', 'A', 'A', 'C', 'G', 'A', 'G', 'C', 'G', 'C', 'C', 'G', 'C', 'A', 'C', 'C', 'C', 'G', 'G', 'A', 'C', 'A', 'T', 'T', 'T', 'T', 'T', 'T', 'G', 'C', 'G', 'G', 'T', 'T', 'T', 'C', 'T', 'G', 'A', 'G', 'G', 'C', 'G', 'C', 'G', 'A', 'G', 'G', 'C', 'C', 'T', 'G', 'A', 'T', 'A', 'A', 'A', 'C', 'G', 'C', 'C', 'C', 'G', 'G', 'A', 'C', 'A', 'G', 'G', 'A', 'A', 'C', 'T', 'C', 'C', 'A', 'A', 'A', 'T', 'T', 'C', 'G', 'A', 'G', 'A', 'T', 'T', 'T', 'T', 'T', 'G', 'C', 'T', 'C', 'C', 'G', 'G', 'A', 'C', 'G', 'G', 'G', 'A', 'G', 'A', 'C', 'C', 'G', 'G', 'G', 'A', 'A', 'C', 'C', 'T', 'G', 'T', 'A', 'T', 'C', 'G', 'G', 'G', 'C', 'C', 'T', 'T', 'T', 'A', 'T', 'C', 'G', 'A', 'G', 'G', 'T', 'A', 'T', 'T', 'G', 'G', 'G']
['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'G', 'C', 'C', 'A', 'A', 'T', 'T', 'T', 'G', 'C', 'G', 'A', 'A', 'A', 'C', 'G', 'A', 'G', 'C', 'G', 'C', 'C', 'G', 'C', 'A', 'C', 'C', 'C', 'G', 'G', 'A', 'C', 'A', 'T', 'T', 'T', 'T', 'T', 'T', 'G', 'C', 'G', 'G', 'T', 'T', 'T', 'C', 'T', 'G', 'A', 'G', 'G', 'C', 'G', 'C', 'G', 'A', 'G', 'G', 'C', 'C', 'T', 'G', 'A', 'T', 'A', 'A', 'A', 'C', 'G', 'C', 'C', 'C', 'G', 'G', 'A', 'C', 'A', 'G', 'G', 'A', 'A', 'C', 'T', 'C', 'C', 'A', 'A', 'A', 'T', 'T', 'C', 'G', 'A', 'G', 'A', 'T', 'T', 'T', 'T', 'T', 'G', 'C', 'T', 'C', 'C', 'G', 'G', 'A', 'C', 'G', 'G', 'G', 'A', 'G', 'A', 'C', 'C', 'G', 'G', 'G', 'A', 'A', 'C', 'C', 'T', 'G', 'T', 'A', 'T', 'C', 'G', 'G', 'G', 'C', 'C', 'T', 'T', 'T', 'A', 'T', 'C', 'G', 'A', 'G', 'G', 'T', 'A', 'T', 'T', 'G', 'G', 'G', 'G']
85945
1793

**Comment by GenomeRIK** [comment] 2020-02-14 12:09
Hello HegedusB,

First off, I just wanted to check that you are using Python 2.7 to run this? 

Moving on, there are a few reasons why this could be happening:
1.  The BAM file from desalt has a CIGAR string that does not match the alignment sequence reported. 
2. The alignment occurs at the end of the genome scaffold.
3. If you used Python 3 to run the script, there may have been issues with the calculations due to syntax differences. 

Could you send me the BAM line where this error occurred? It will be the line after the last read represented in the read.txt file. If you are having trouble finding it, let me know and I will add another line to the error report so that you can re-run and get the read ID. 

Also could, you let me know what the scaffold length is for this BAM line?

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-14 15:46
Hi Richard,

I am using the Python 2.7.5. 
The asked BAM line:
68:2191|8a1e69dc-0e1c-4abd-8fca-8f5eb6039001    0       scaffold_102    83929   60      2S295M57N292M56N423M61N103M50N678M2D163M176S    *       0       0       GAAAAGGTTGTTCCTCAACCGCCATCATCAACATCCTACAGGGCCCCTCAAGGCTTATTTTCAATGTCTGATTACCGCTAGCTACAGGTCGCCAACAACGAGCTGCGCAGCTTATACCCACAAACACAAGGCAGCGCTTGAGAAACCCCTGCATCTATACCAGCGTTGCAAAGGGATGGTCGCGGCTCTTCTGCCAGTTATTTCGCCTCTGGGGACAAGATGAGGGTGTTTCTTCAAGAATCCCCCTTTCCAGGCTTTGTTTGAGCTTCGAAGAAAGGCGGGCAAGGTCGTGAATCGGCAATCTGCCTACTTCTCAGAAGACCTGTGGACGTTGTGAACACCCGAACCGCGCTGTCTGCAAGAGGCCTTGGTACATACACGCCCCCTTCGTGATATATCTTCGAGAACCAGACCGGGTCGCAGCCAGTCTCGTGAACCAGACGGGAGAACGATTATCTTGTCCAATGAATCGAGTCTTTGTTCGCGAGGATAAACTCATGGCCAGGCACCAGACAGGCCATCGTACTCGACTCCTAACAGAGTTTTTACGCCGTGTCTCTAGACAGTAGCTTCGTAGAAGCGTTTCGAGAACCTCGCTGTACTTACTTCAAAGGAATAACTTGGATCAGGATGAATGTAGCAACTTCAGAAGTTCCAATGGACCCCAGTAAACCGATTCCTCTCGGTTCTCGCAAGCAAGTTATCAGCGTGCCTAAACCGCACCGGTTGGCGAAATTCCATCTGACTTCTTACGGATATCTGGTCGCGCACTACCGTATAGGAATAGCTGATTGATCACCTGGTCGCACCAAAGCACGCCAAAACCCGTTGGAAAACCGGATGGTTTCACCCTGAACGAGAAAGCATCTGGGAAGCGCGAATGCTGAACCAGTACGTGGTGTCCTCAAGTACATTCCCTCTTGGCTCCTGGAGCCGGGTGGCAAGAGTATCTTCGGCGATGCGCAGAGATCACTTCGTATTCTCTCGAGATAGGCCTTTCAATGATGCGATGACGAAAGGAACCACTTTCCTGCCGGACCCCTGGTAAGGGCGTCGACATTCATGAGGGCGGCGGGCTTCGATCCAGACGTCGCTGCATTTGGCTGTGGTCGTCGACGATTGGCCCAGGCCGACATCTAAGCCACGACTCGCTCCTCTACATGACTGCGTCCCGCCTATCCATCTTCAACGCACGCGAAGAGCAAGGAGGGAAACCCTTGAAACTAGAGATCACCTCGGCGCTGATGCCATAAGTGCGGTTCTTCCGTTCTCACTTTCCGCTCTAAACGAAAGGGACGATCCTGATGCCTCGCTGAAAATGGGATGTAGGAAATTTGTCCCGTTCAAATGCGAGATCGTGCCTCGTTCGGGAGGCATGCTGCTTTAATTCGGTCATTGGGGTAATAACTTGGCAGTTCATTTCAACCGGTGACCTACCTTTCTTTCTGTCTAGAAGTTCTGAAGGTGTGCAAAGTACGTACAGCAACACCGAGTAAACGGCCCTGAAAGATGGAACGTGCATTTGTGTACCTCCGACTCCACTCCTCCAAATAAGCGCCGACTTCTGAATGCCCGCCAGTGGAGAGTATCAGATGGCAGCGCGAATGGACACCCGTCCAGACCACCGCCAAGAGGACCCCCCAAAATCTCGACGAAGGTCCGAGCGGATTCCGGACAGGATTTTCAGGTTTTGGGGACAGGCTGGAGGTCAAATCCGGACAGAAAAGGGAATTTTGAGGCCGCAAGGCCAGTGAAATCCCGGACAAAATTGGCATTTTTGGCCTCAACGGCGGAAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGGGGTCCTCCGCCAAGGGCCTCCTGCATGCCAACGAGGCGCGAGACCAACGTCATCGAAGCCCAAACGTTTCATCTCGTTTGGACCCCAGTTTCCCGGTAAGCCTAGTCGGACACCCAGAGCCCAAATTTCGCGCTCAAAACGGAAGACCAAGAGTATTATTTTTTGCGTAAAAGAAA      *       NM:i:2  ms:i:1946       AS:i:1944nn:i:0

The scaffold length for the BAM file is 86107 bp. As I see the aligned read end hanging down from the scaffold.

I ran the python tama_collapse.py with a minimap2 produced BAM file and it is running seemingly good.  Form me the minimap  unfortunatelly is not feasible because it handles the short exons terrible.

Thanks for the help,
Botond

**Comment by GenomeRIK** [comment] 2020-02-14 16:10
Hi Botond,

Ok, this is quite an interesting case! It appears that the issue is both 1 and 2. 

The Desalt BAM Cigar line says the last exon is 163M. So this should be 163 bases. However, when TAMA tries to extract these 163 bases, the last base coordinate falls outside of the scaffold. 

To confirm this, could you copy/paste the last 163 bases from "scaffold_102"?

If this is true, then this is a bug in Desalt which needs to be fixed. I suspect the bug stems from handling cases where there is a clipping which occurs due to falling off the end of the scaffold. 

Once we have confirmed that this is the issue you can either choose to report this bug to the Desalt developer or if you wish I can report. However, since this was found in your data it will be harder for me to provide the developer with the information necessary to fix the bug. 

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-17 08:16
Hi Richard,

>scaffold102_last163bp
AAAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGG

I have copied the asked sequence. Based on your replay it seems to me the problem is much more complicated than I first expected. If your assumptions are right I will contact with the deSALT developers. Thank again for your help!

I have an other question. I am working with fungi transcriptiome where it is not rare that transcripts from neighboring genes are overlapping with each other in a short region. In these cases the clustering method join these overlapping transcripts into one gene. Can you suggest which parameter should I use to avoid this.

I attached an example:  
![scaffold_1_e1](https://user-images.githubusercontent.com/9871809/74634986-58b49d80-5165-11ea-9afd-a702e7ddad8d.jpg)

**Comment by GenomeRIK** [comment] 2020-02-17 13:04
Hi Botond,

Ok so from the scaffold sequence, I think it is pretty clear that this is an issue with Desalt and the way it generates the CIGAR string. 

So you can see from your read sequence that the last exon should be 163 base pairs:
"G [splice junction] AAAAAAAACGCCAATTTGCGAAACGAGCGCCGCACCCGGACATTTTTTGCGGTTTCTGAGGCGCGAGGCCTGATAAACGCCCGGACAGGAACTCCAAATTCGAGATTTTTGCTCCGGACGGGAGACCGGGAACCTGTATCGGGCCTTTATCGAGGTATTGGGG  [end of mapping] G"

So the scaffold sequence ends with "GGTATTGGG" thus the

**Comment by HegedusB** [comment] 2020-02-17 15:46
Hi Richard,
Thanks for the quick and detailed answer.
I think you are more competent then me to describe the error for the desalt developers. If you do not mind I would like to ask you for that. Do you need the full size sorted bam file (it is a little larger than 2G)? Is it good for you if I upload the files on to my gdrive and share with you the download link?

In fungi it is really common that the transcripts UTR regions overlap with each other. A solution which can handle this problem could be really useful. I will try out the suggested parameters and I would be really happy for any new features which make it possible to better cluster the long reads.

Thank you,
Botond

**Comment by GenomeRIK** [comment] 2020-02-18 01:02
Hi Botond,

Could you send me:
1. A fasta file with just the read where the error occurred
2. A fasta file with just the scaffold where the read mapped

I think this may be enough for the Desalt developer to figure out the bug. 

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-18 12:08
Hi Richard,
I upload the requested files here.

1. nanopore_reads_from_scaffold_102_edge.fa: A fasta file with the reads where the error occurred, and some additional reads which are located on the same end and also overhanging

2. Copci_scaffold_102.fasta : fasta file where the read mapped

Thank for the help! 
Botond

[Botond_scaffold_102.zip](https://github.com/GenomeRIK/tama/files/4219062/Botond_scaffold_102.zip)

**Comment by GenomeRIK** [comment] 2020-02-18 17:12
Hi Botond,

Ok I have submitted the issue on the deSALT repo. You can find it here:
https://github.com/ydLiu-HIT/deSALT/issues/19

Hopefully it gets fixed soon. I am going to close this issue but feel free to open up a new issue regarding the gene splitting or any other issue you run into.

Thank you,
Richard

**Comment by GenomeRIK** [comment] 2020-02-19 02:51
Hi Botond,

The deSALT developer replied to the issue. Apparently when he tried to map the read to the scaffold the resulting CIGAR string was ok. Perhaps you are using an older version of deSALT? He tested this on v1.5.2. What version are you using?

Could you have a look at the issue thread?

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-21 12:34
I have tried out the corrected deSALT mapper. Now I have got a little different error.
Error:

Genome seq is not the same length as query seq
[]
['C', 'G', 'G', 'T', 'C', 'C', 'T', 'G', 'C', 'A', 'G', 'A', 'T', 'G', 'G', 'A', 'G', 'G', 'G', 'G', 'G', 'C', 'T', 'C', 'G', 'G', 'C', 'T', 'C', 'T', 'G', 'T', 'C', 'A', 'G', 'G', 'G', 'A', 'C', 'G', 'G', 'C', 'A', 'T', 'A', 'G', 'C', 'T', 'C', 'T', 'T', 'C', 'C', 'T', 'C', 'C', 'A', 'C', 'C', 'A', 'T', 'T', 'C', 'C', 'G', 'A', 'G', 'A', 'G', 'T', 'G', 'T', 'C', 'C', 'C', 'T', 'T', 'T', 'C', 'T', 'C', 'C', 'C', 'C', 'C', 'T', 'T', 'G', 'G', 'A', 'A', 'T', 'C', 'T', 'C', 'C', 'T', 'A', 'C', 'C', 'A', 'T', 'C', 'C', 'A', 'C', 'C', 'A', 'G', 'T', 'T', 'T', 'C', 'G', 'T', 'T', 'T', 'C', 'T', 'C', 'T', 'G', 'T', 'C', 'G', 'T', 'T', 'T', 'G', 'G', 'G', 'C', 'C', 'T', 'C', 'G', 'A', 'C', 'A', 'T', 'C', 'C', 'T', 'T', 'T', 'G', 'G', 'A', 'T', 'T', 'C', 'T']
78582
119

# this is the problematic alignment 
66:354|771937c0-05dc-46eb-8001-426b56fc5069     0       scaffold_114    78583   60      119S152M        *       0       0       GTGGGTTACCAACTGTTAGTCGCAGGCGGCTGTTCTTCATCTACACTGTTCTTCTTCCCGACGCCACGCAAGGCGCCTTTGCGCGTGAGAACGGAGCGAAGGCGCTGGAGGGACGTGCGCGGTCCTGCAGATGGAGGGGGCTCGGCTCTGTCAGGGACGGCATAGCTCTTCCTCCACCATTCCGAGAGTGTCCCTTTCTCCCCCTTGGAATCTCCTACCATCCACCAGTTTCGTTTCTCTGTCGTTTGGGCCTCGACATCCTTTGGATTCT *       NM:i:1  ms:i:147        AS:i:147        nn:i:0
51:1174|2ddaa373-373d-4a63-b9d3-beecb6a47896    272     scaffold_115    2       0       621S267M2D60N89M1D151M  *       0       0       *       *       NM:i:7  ms:i:472        AS:i:473        nn:i:0

# the length of the scaffold (scaffold_114) is 78582 bp

**Comment by GenomeRIK** [comment] 2020-02-21 13:54
Hi Botond,

I have been following the issue thread on deSALT as well. Thank you for taking the time and effort in helping us debug this issue.

This new BAM line does not make sense to me. If the scaffold is 78582 bp long, how can the alignment start at a coordinate (78583) beyond the last bp of the scaffold? 

And to add to the weirdness, the alignment shows that it starts with 119 soft clipping (119S152M). So basically this bam line is saying that it soft clipped the first 119 bases of the read and then aligned the remainder of the read to coordinates that do not even exist in the scaffold. 

So this is definitely an issue with deSALT. 

I will copy/paste that BAM line and write a comment on the deSALT thread describing this error. 

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-24 11:59
Hi Richard,
I have got an other error message. This is different than the others was.

Error with exon end earlier than exon start
130499  130499
['54:320|c8fdeedc-6acd-4317-bf96-a5f2afaf8975', '65:484|dd4e005e-d9a8-4f8f-91ac-664d5daf0a47', '60:611|90fe6654-3339-4d91-83fe-aba1dc933a88', '68:544|a8b8655f-98f3-4051-8b37-eb924ff182db', '59:746|714dabfc-23aa-4ed8-bb81-336cce4b383e', '71:943|0799408b-31e5-4d96-800c-91b7d0e57da9', '79:367|7139d621-37c6-471e-a0b3-7c54e24c280d', '65:595|33ac2c73-a646-4ba9-b75b-85024017af39']

Do you have any ideas?

I copy here some of the reads listed in the error message:
54:320|c8fdeedc-6acd-4317-bf96-a5f2afaf8975     0       scaffold_23     132838  60      179M1D94M       *       0       0       CCAGGATATCTTGACTCTTGGCAGAGGGCAAAGATCTATGGGTAGATTGTGTTCACCTTCCTGTGACCTCGTCCCTCTCAGCCCGGGCTCGCCGTCCTCACCGCTCTATCCATCCCTTCACTCTTCTACTCGATCTCGCTTAGCCTTGTACATATGCTCTACTGTCGTATCCTTCCTTCTTTGTCGATCTCCCCTTGCATTCTTGGACCTACTTAGTGCACATTGATCTCGAAACCTTGTAACCCTGTTGATGAATGACATGCTATTTCGATC    *       NM:i:4  ms:i:251        AS:i:251     nn:i:0

65:484|dd4e005e-d9a8-4f8f-91ac-664d5daf0a47     0       scaffold_23     132710  60      414M    *       0       0       GGGTGAACTGGGACCGCTTGGTGGAGGTTAAGAAGAAATACGACCCTAAGAACATTTTCAGCAATAGCTTCTGGCCTTTGAATGAACATGGTGAAATGGTCGACCCCCGCACCCATGGGCCACCCACCCCAGGATATCTTGACTCTTGGCAGAGGGCAAAGGTCTATGGGTAGATTGTGTTCACCTTCCTGTGACCTAGTCCCTCTCAGCCCGGGCTCGCCGTCTTCACCGCTCTATCCATCCCTTCACTCATCTACTCGATCTCGCTTAGCCCTGTACATATGCTCTACTGTCGTATCCTTCCTTCTTTTGTCGATCTCCCCTTGCATTCTTGGACCTACTTAGTGCACATTGATCTCGAAACCTTGTAACCCTGTTGATGAATGACATGCTATTTCGATCAAATGGCTACAA    *       NM:i:4  ms:i:394        AS:i:394        nn:i:0

60:611|90fe6654-3339-4d91-83fe-aba1dc933a88     0       scaffold_23     132456  60      38M68N51M51N108M1I14M1I326M     *       0       0       ATGCCAATGATGATCGGTGTATCGATTCTGCTGAGGAGTGGATTGTAGGGACCTTGAAGCCCGTGCACATCGGCGGCGCATTCGCTAGCTTCTTTGGAAGGCGTGAGATTCCAGAGCGCATTAAAGCTTCTTTCGGGGTGGACTGGGACCGCTTGGTGGAGGTTAAGAATAAATACGACCCCAAGAACAATTTCAGCAAATAGCTTCTGGCCTTTTGAATGAACATGGTGAAATGCTCGACCCCCGCACCCATGAGCCACCCACCCTAGGATATCTTGACTCTTGGCGGAGGGCAAAGATCTATGGGTAGATTGTGTTCACCTTCTTGTGACCTCGTCCCTCTCAGCCCAGGCTCGCCGTCTTCACCGCCCTATCCATCCCTTCACTCATCTACTAGATCTCGCTTAGCCCTGTACATATCCTCTACTGTCGTATCCTTCCTTCTTTTGTCGATCTCCCCTTGCATTCTTGGACCTATTTAGTGCACATTGATCTCGAAACCTTGTAACCCTGTTGATGAATGACATGCTATTTCGATC    *       NM:i:20 ms:i:433        AS:i:431        nn:i:0

Botond

**Comment by GenomeRIK** [comment] 2020-02-24 12:34
Hi Botond,

Could you send me the bam lines of all of the reads listed in the error output?

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-24 17:59
Hi Richard,
Here are the reads.
[problematic_reads_20200224.zip](https://github.com/GenomeRIK/tama/files/4245999/problematic_reads_20200224.zip)

Botond

**Comment by GenomeRIK** [comment] 2020-02-25 01:46
Hi Botond,

Sorry but can you send me the "trans_read.bed" file lines corresponding to these reads?

They should be all at the end of the file since that is where TAMA would have stopped writing out. 

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-02-28 08:27
I am sorry for the late answer, out server was turned off due to maintenance. 
I checked the reads in the trans_read.bed file but they are not there.

**Comment by HegedusB** [comment] 2020-03-05 13:36
Hi Richard,
I repeated the run and got the same result. 
"""
Error with exon end earlier than exon start
130499  130499
"""
The reads which probably causing the problems are not in the trans_read.bed and in the result bed file. What do you think? What could be the problem?

Botond

**Comment by GenomeRIK** [comment] 2020-03-05 16:32
Hi Botond,

Apologies for not responding sooner. Would you be able to send me the fasta file for "scaffold_23"? 

In order to understand what is going on, I need to be able to see the transcript models from the mapping so I can get this from the trans_read.bed file or I can generate them if I have the bam lines and the scaffold fasta. 

Also there is a real non-bug reason why this error typically occurs which I explain a bit in this issue thread:
https://github.com/GenomeRIK/tama/issues/14

But I would like to check your error personally to see if this is indeed the case and what the best solution is. 

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-03-06 08:54
Hi Richard,

I am sanding the "scaffold_23" fasta files and the bam lines referring to the reads appeared in the error massage. I hope you can figure out what could be the probleme.
[error_notification_20200306_dir.zip](https://github.com/GenomeRIK/tama/files/4297369/error_notification_20200306_dir.zip)

Thank you,
Botond

**Comment by GenomeRIK** [comment] 2020-03-06 13:57
Hi Botond,

I just ran this data through TAMA Collapse using your parameters and I didn't get any errors. 

Are you using the same parameters as you originally posted?
Could you send the entire bam file and reference fasta? Or at least all the bam lines from "scaffold_23"?

I need to recreate the error to understand what happened.

Thank  you,
Richard

**Comment by HegedusB** [comment] 2020-03-06 15:35
Hi Richard,
This is the command what I am using:
tama_collapse.py -s sorted.bam -b BAM -f ref_genome.fasta -p strain_name -x no_cap -icm ident_map -a 100 -z 100

This is the entire scaffold_23 bam file. I hope it helps.
[Copci_scaffold_23_sorted.zip](https://github.com/GenomeRIK/tama/files/4299028/Copci_scaffold_23_sorted.zip)

Botond

**Comment by GenomeRIK** [comment] 2020-03-06 23:33
Ahah!! Wow this was a weird one! Definitely had me scratching my head but the answer was right there in the beginning. 

The issue is coming from yet another issue with the CIGAR string from Desalt.
Take a look at the offending read bam line:
71:943|0799408b-31e5-4d96-800c-91b7d0e57da9     0       scaffold_23     130155  60      1S136M59N14M135N985N704N46N56M52N152M68N51M51N353M1D107M        *       0       0       GGCTTCCCAAGCTACACCTCGAGTTATTCTTTGTTTCCCCTCTCCATGATGCTCACTCCCAAATCTCTGGATCAGGACCTCTACGACGAGCTGTCGTCTCTCTGTAGGGGCCCTGTCGTGCTCAACGACGACCCAGACTTCGTAAATTATGCGACGACATTATCCATACGACGGTTGAACAATTCAGCAACACTCCGCTTGGTTGCACGTGGCTTTTCGAATTGGCGGGAGGCGCCGTTGGGGAGTTTACGGATTCCGTGGTCCCGAAGGCTCAAAGGGAAGCGTTGTTCAACATCGTGGCACTCCACCAGTGTGAGATGGATGCCAATGATGATCGGTGCATCGATTCTGCTGAGGAGTGGATTGCAGGGACCTTGAAGCCCGTACACATCGGCGACGCATTCCCTAGCTTCTTTGGAAGGCATGAGATTCCAGAGCGCATCAAAGCTTCTTTCGGGGTGAACTGGGACCGCTTGGTGGAGGTTAAGAAGAAATACGACCCCAAGAACATTTTCAGCAATAGCTTCTGGCCTTTGAATGAACATGGTGAAATAGTCGACCCCCGCACCCATGAGCCATCCACCCCAGGATATCTTGACTCTTGGCAGAGGGCAAAGATCTATGGGTAGATTGTGTTCACCTTCCTGTGACCTCGTCCCTCTCAGCCCAGGCTCGCCGTCTTCACCGCTCTATCCATCCCTTCACTCATCTACTCGATCTCGCTTAGCCCTGTACATAT


If you look at the cigar string, there is something very weird:
1S136M **59N** 14M 1**35N 985N 704N 46N** 56M **52N** 152M **68N** 51M **51N** 353M1D107M

I made all the N values bold. N values represent the intronic regions. The issue is that there is a string of N blocks side by side **35N 985N 704N 46N**. This does not make sense since there needs to be something else between the N's or else they should all be represented as the total length of the string of N's. I am not sure why Desalt is doing this but it could be micro-exons that are not being represented correctly in the CIGAR string.

The reason for the TAMA error is because TAMA checks that each exon has a positive length. If an exon does not have a positive length, you get that error. There are other reasons that can cause this as well. 

I guess we will need to go back to Yadong for this one. 

Would you like me to post another issue thread for this like last time or would you like to post it?

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-03-07 09:50
Hi Richard,
Would you please. I think you can explain it more clearly than i could. I am really sorry because you have to work so much on this and appreciate it really much! 
Thank you,
Botond

**Comment by GenomeRIK** [comment] 2020-03-07 10:42
Hi Botond,

It's no problem. It's important to get this working for your research and others who will be using the same tools. 

Thank you for taking the time and effort to make sure we solve these problems. Many people just give up and either ignore the problems or just use other tools where the problems could just be silent errors. 

I have posted this issue on the Desalt github. You can find it here:
https://github.com/ydLiu-HIT/deSALT/issues/25

Could you send the scaffold fasta and reads to Yadong for testing?

Thank you,
Richard

**Comment by HegedusB** [comment] 2020-03-09 12:49
Hi Richard,

Thank your for the help. It seems like the deSALT and the tama are working now together with my short test data set. I will extend this data set in the future and hopefully there wont be any additional issues.
In the next step I want to use the "tama_read_support_levels.py" get the read support for the transcripts.
The command what I tried is this: 
tama_read_support_levels.py -f tama_file_list.txt -m Copci_v1.bed -o Copci_v1 -mt tama

The tama_file_list.txt contain is:
"Copci_v1        Copci_v1_trans_read.bed trans_read"

At the and I got this error massage:
"""
opening filelist file
opening merge file
Traceback (most recent call last):
  File "/SSD/software/tama/tama_go/read_support/tama_read_support_levels.py", line 270, in <module>
    read_list = list(source_trans_read_dict[source_name][source_trans_id].keys())
KeyError: ''
"""

What do you think? What is the mistakes what I made?

Thank you,
Botond

**Comment by GenomeRIK** [comment] 2020-03-09 13:39
Hi Botond,

Are you using tab delimiters for "tama_file_list.txt"?

Cheers,
Richard

**Comment by HegedusB** [comment] 2020-03-09 16:22
Hi Richard,
Yes, I was using tab delimiters : "Copci_v1\tCopci_v1_trans_read.bed\ttrans_read"
Botond

**Comment by GenomeRIK** [comment] 2020-03-09 22:08
Hi Botond,

Ok I just realized that your command line is wrong for this use case.

It should be:
tama_read_support_levels.py -f tama_file_list.txt -m no_merge -o Copci_v1 

Also avoid using underscores in the source name since I use underscores as a delimiter in the output.

Let me know if that works.

Cheers,
Richard

**Comment by HegedusB** [comment] 2020-03-10 10:26
Hi Richard,
Thanks a lot! That was the mistake! Now it is working fine!
I have one last question for now. I am using Lexogen TeloPrime protocol for the nanopore library preparation. The TeloPrime protocol promise in a certain extent full length transcripts (cap, polyA selection). The question is, could I use the "tama_read_support_levels" outputs trans_read_count data to express the number of full-length reads which support that transcript.
Botond

**Comment by GenomeRIK** [comment] 2020-03-10 11:21
Hi Botond,

If you run TAMA Collapse with the "capped" mode then "tama_read_support_levels" will give you all full length reads which support each transcript model.

However, if you run it with "no_cap", then "tama_read_support_levels" will give you any reads that fit within the full length model even if the read does not cover the full length. It will assume that sub-full length reads are just degraded products of the full length transcript. 

Also if you are using Nanopore you may want to take a look at an issue with respect to read filtering and using pychopper:
https://github.com/nanoporetech/pychopper/issues/26

Cheers,
Richard

**Comment by HegedusB** [comment] 2020-03-10 14:46
Hi Richard,

Thanks for the advice. I will try out the "capped" parameter.  My fear is that, it will produce lots of fragmented transcripts because the teloprime is really sensitive to the good quality cDNA library. If the library is not so good, the 5prime-cap do not works reliable. 
I will check the pychopper output again. I am using a little different approach. Because my samples are bar coded I am using the concatenated bar-code+teloprime adapters which improves the pychopper sensitivity a lot.

Cheers,
Botond

**Comment by GenomeRIK** [comment] 2020-03-11 17:33
Hi Botond,

Ok I am closing this thread now. Please feel free to start a new thread if you have more issues. 

Thank you,
Richard

**Closed by GenomeRIK** 2020-03-11 17:33 UTC
