### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by Anne-oxford** [GenomeRIK/tama#2] opened 2017-12-07 14:32 UTC
Hi ,

I'm trying to run the collapse script of pacbio data mapped with map but I keep getting this error and haven't figured out why.

Traceback (most recent call last):
  File "tama_collapse.py", line 2426, in <module>
    [h_count,s_count,i_count,d_count,mis_count,nomatch_dict] =  calc_error_rate(start_pos,cigar,seq_list,scaff_name,read_id)
  File "tama_collapse.py", line 409, in calc_error_rate
    genome_slice = fasta_dict[scaffold][genome_start:genome_end]
KeyError: 'chr1'

**Comment by Anne-oxford** [comment] 2017-12-20 17:48
I had to edit the script a bit, some of the dictionaries were called incorrectly. I'm trying TAMA merge with some short read data and I keep running out of memory even with just two short read datasets 50M reads each. Any idea how I could make this more memory efficient?

**Comment by GenomeRIK** [comment] 2017-12-24 14:38
Hi Anne, 

Sorry for the late response, I didn't see this until just now. 

Are you trying to merge bed files that are transcript assemblies from short read datasets or bed files representing the short reads themselves? How many lines are in each bed file you are merging?

Also could you let me know what was the issue with the dictionary calling? I have a feeling it has something to do with the formatting of the fasta headers.

Thank you!
Richard

**Comment by Anne-oxford** [comment] 2017-12-28 21:20
Hi Richard,

Happy holidays and and thanks for getting back to me. I might have got it wrong but the fast dict key is scaffold in some line and seqname in other and had to change to seq_name to get it to get it to work. The bed file was the reads and not transcriptome which probably accounts for the running out of memory for sure.
One more question, is there a way to deal with 5’ fragmentation ?

Regards,
Anne

**Comment by GenomeRIK** [comment] 2017-12-28 22:21
Hi Anne,

Happy holidays to you too! Could you send me a link to the fasta file you are using? I would like to see how the fasta headers are formatted. The change in variable name is intended and functional. It is meant to segment the different defs. I am concerned that your change may have unintended outputs. If possible I would also like to see the headers for the sam file. Basically the issue is some mismatch between the representation of scaffolds in the fasta file and the sam files. 

As for merging the bed files representing RNAseq reads, can I ask what is the motivation for doing this? TAMA merge is meant to merge transcriptome annotations, especially with respect to resolving splicing differences. It was not designed for the size of RNAseq read datasets. However, if this is useful I can see about working on the memory management for datasets of that size. 

By 5' fragmentation are you referring to RNAseq having diminishing coverage on the 5' end of transcripts? If so, many transcript assembly software have ways of dealing with this in RNAseq data, however, there is no way to know for sure that the 5' end in RNAseq data is real.

If you are referring to 5' degradation leading to lost 5' ends from Iso-Seq data, it is very similar to the issue in RNAseq short read data. The best way to avoid this is to do 5' cap selection on your RNA libraries before sequencing. However, if you are dealing with Iso-Seq data that was produced from non-5' cap selected libraries then there are 3 main approaches that I know of:
1. Collapse matching transcripts to the longest 5' end (The official Iso-Seq pipeline does this and you can also do this with TAMA Collapse).
2. Use CAGE sequencing to get 5' ends and match up to the Iso-Seq models.
3. Use some other verified annotation to compare 5' ends. 

Methods 2 and 3 can also be used for short read RNAseq data. 

However, none of these are ideal because you still can't be sure that you are matching the 5' ends correctly. 

If this is not what you meant by 5' fragmentation, could you please explain further. 

Thank you,
Richard

**Comment by Anne-oxford** [comment] 2017-12-30 00:15
Hi Richard,

Thanks for getting back to me. I can work on getting some sample files to you.
My fasta header looks like


>cb10992_c3/f1p0/3477 isoform=cb10992_c3;full_length_coverage=1;non_full_length_coverage=0;isoform_length=3477;expected_accuracy=0.996

While my sam header looks like


@HD     VN:1.0  SO:coordinate

@SQ     SN:chr1 LN:249250621

@SQ     SN:chr2 LN:243199373

@SQ     SN:chr3 LN:198022430

@SQ     SN:chr4 LN:191154276

@SQ     SN:chr5 LN:180915260

@SQ     SN:chr6 LN:171115067

@SQ     SN:chr7 LN:159138663

@SQ     SN:chr8 LN:146364022

@SQ     SN:chr9 LN:141213431

@SQ     SN:chr10        LN:135534747

@SQ     SN:chr11        LN:135006516

@SQ     SN:chr12        LN:133851895

@SQ     SN:chr13        LN:115169878

@SQ     SN:chr14        LN:107349540

@SQ     SN:chr15        LN:102531392

 And the mapping line


cb18086_c57499/f1p1/3151        16      chr1    14409   40      47M5I374M140N69M757N108M1I44M659N159M92N198M177N136M237N137M172N147M206N1726M

**Comment by GenomeRIK** [comment] 2017-12-30 01:47
Hi Anne,

So when you run TAMA collapse your command line should look like this:
python tama_collapse.py -s <samfile> -f <fasta> -p <prefix> -x <capflag>

So the fasta header that you showed me is from the fasta file that you use for <fasta>? If so, this is the issue. The <fasta> file should be the fasta file for the genome assembly that the sam file is based on. I believe you have used the fasta file for the Iso-Seq sequences. This would explain why the scaffold name is not matching. TAMA collapse is trying to match the scaffold names in the sam file to the scaffold names in the fasta file. 

If you did use the genome assembly fasta then could you send me the fasta header from that file?

Cheers,
Richard

**Comment by Anne-oxford** [comment] 2017-12-31 15:32
Hi Richard,


What a silly mistake yes that was the issue! Thanks you so much for the help. One more thing,  I’ve attached a screenshot of an example. The longer transcript is collapsed into a shorter  one. The library is not capped so so I’m using the no_cap option. I’ve checked and the read is accepted for collapsing but regardless of the options I use it’s collapsed to a shorter transcript. Any idea why this would be?

Best wishes and have a Happy New Year!!!!

Anne

**Comment by GenomeRIK** [comment] 2017-12-31 16:10
Hi Anne,

I see you are responding via email instead of posting on the issues board. Because of this I am unable to see your attachment. Could you either send it to my email (GenomeRIK@gmail.com) or post it on the issues board?

Also it would help if you sent me the command line you submitted and the excerpts from the "cluster.bed" file for this transcript.

Thank you,
Richard

**Closed** 2018-01-07 00:36 UTC
