### ISSUE TITLE
TAMA GO - contradicting results based on Aligners

### ISSUE THREAD

**Issue by SziKayLeung** [GenomeRIK/tama#14] opened 2019-08-05 10:40 UTC
Hello Richard, 

I was trying out the TAMA Go degradation tool and found quite drastic differences depending on the aligner used: 

**Aligned with Minimap**
minimap2 -t 30 -ax splice -uf --secondary=no -C5 -O6,24 -B4 $REFERENCE/mm10.fa $1.flnc.fasta > $1.sam 2> $1.minimap_map.log
samtools sort -O SAM $1.sam > $1.sorted.sam

B21_degradation.txt, aligned with Minimap2
Degradation Signature = 0.947700974421
K17_degradation.txt, aligned with Minimap2
Degradation Signature = 0.942204249062
K23_degradation.txt, aligned with Minimap2
Degradation Signature = 0.938241261273

**Aligned with GMAP**
gmap -D $REFERENCE -d mm10 -f samse -n 0 -t 16 --cross-species --max-intronlength-ends 200000 -z sense_force \
        $1.flnc.fasta > $1.sam \
        2> $1.gmap_map.log
samtools sort -O SAM $1.sam > $1.sorted.sam
		
B21_degradation.txt, aligned with GMAP
Degradation Signature = 0.45011328759
K17_degradation.txt, aligned with GMAP
Degradation Signature = 0.38691335822
K23_degradation.txt, aligned with GMAP
Degradation Signature = 0.364736473647

Of course I understand that this is to do with aligner issue but was wondering whether you see this with your samples, and given the conflicting results, which aligner do you trust more? 

Thank you,
 
Best wishes, 
Szi Kay

**Comment by GenomeRIK** [comment] 2019-08-07 01:05
Hi Szi Kay,

Apologies for the delayed response. This is quite interesting and I have not seen a difference like this between minimap2 and gmap in my analyses. 

Could you send me some information so I can get a better idea of what might be going on?

Information needed:
1. Command/parameters used for both the nocap and capped runs of TAMA collapse 
2. Number of accepted reads from the prefix_read.txt file for the TAMA collapse runs on both the minimap2 and gmap results. 
3. Number of reads in the prefix_strand_check.txt files for both mappers.
4. Number of genes and transcript models from each of the TAMA collapse runs? (no_cap,capped,minimap2, gmap)

The degradation signature of over 0.90 for the minimap2 result looks very suspicious. I think there may be something else going on here. 

Thank you,
Richard

**Comment by SziKayLeung** [comment] 2019-08-12 18:18
Hi Richard, 

Apologies also for the delayed response. I think you are right, there is something suspicious with minimap2, especially with the discrepancy in number of transcripts between the models (see 4). 

1.	Command/parameters used for both the nocap and capped runs of TAMA collapse
python $TAMA/tama_collapse.py \
-s $1.sorted.sam -f $REFERENCE/mm10.fa -p $1_nocap \
-d merge_dup -x no_cap -a 100 -z 100 -sj sj_priority &> $1.tama_nocap.log 

python $TAMA/tama_collapse.py \
-s $1.sorted.sam -f $REFERENCE/mm10.fa -p $1_capped \
-d merge_dup -x capped -a 100 -z 100 -sj sj_priority &> $1.tama_cap.log

2.	Number of accepted reads from the prefix_read.txt file for the TAMA collapse runs on both the minimap2 and gmap results.
GMAP results: 
Number of accepted reads in B21_nocap_read.txt: 418215
Number of accepted reads in K17_nocap_read.txt: 348668
Number of accepted reads in K23_nocap_read.txt: 376519

Minimap results:
Number of accepted reads in B21_nocap_read.txt: 414927
Number of accepted reads in K17_nocap_read.txt: 341157
Number of accepted reads in K23_nocap_read.txt: 374795

3. Number of reads in the prefix_strand_check.txt files for both mappers.
GMAP results: 
Number of reads in B21_capped_strand_check.txt: 1 
Number of reads in K17_capped_strand_check.txt: 0 
Number of reads in K23_capped_strand_check.txt: 2 

Minimap results:
Number of reads in B21_capped_strand_check.txt: 0
Number of reads in K17_capped_strand_check.txt: 0
Number of reads in K23_capped_strand_check.txt: 0

4. Number of genes and transcript models from each of the TAMA collapse runs? (no_cap,capped,minimap2, gmap) 
Note: Following numbers taken from 4th column in bed file assuming numbers refer to gene:transcript i.e  G1;G1.1 and G1;G1.2 refer to the same gene, but different transcript
GMAP results:
B21_capped.bed: 21385 Genes and 136790 Transcripts
B21_nocap.bed: 	21385 Genes and 78695 Transcripts
K17_capped.bed: 25682 Genes and 126628 Transcripts
K17_nocap.bed: 	25682 Genes and 82436 Transcripts
K23_capped.bed: 22930 Genes and 133018 Transcripts
K23_nocap.bed: 	22930 Genes and 88031 Transcripts

Minimap results: 
B21_capped.bed: 20667 Genes and 129672 Transcripts
B21_nocap.bed: 	2180 Genes and 7219 Transcripts
K17_capped.bed: 24370 Genes and 118407 Transcripts
K17_nocap.bed: 	2620 Genes and 7496 Transcripts
K23_capped.bed: 22407 Genes and 124319 Transcripts
K23_nocap.bed: 	2419 Genes and 8188 Transcripts

Let me know what you think and any additional information needed, 

Thank you, 
Szi Kay

**Comment by GenomeRIK** [comment] 2019-08-12 18:35
Hi Szi Kay,

Ok so it looks like something went wrong with the Minimap2 no_cap runs. The number of genes for a capped run and a no_cap run with the same parameters should always be the same. I suspect that the no_cap runs on minimap2 terminated early for some reason. 

Did you save the terminal output from those runs? If so, can you check that the last thing in the output is:
TAMA Collapse has successfully finished running!

If this is not the last line in the output, can you copy paste the last 10 lines in the output? They should show what error happened. 

If it did finish successfully, can you check the number of lines for the trans_read.bed files?

Cheers,
Richard

**Comment by SziKayLeung** [comment] 2019-08-13 16:24
Hi Richard, 

Tama Collapse did run successfully for the above three samples and was last line in the output. 

Interestingly, though there is quite significant difference in number of lines for the trans_read.bed file for the minimap cap vs nocap:
414927 B21_capped_trans_read.bed
341157 K17_capped_trans_read.bed
374795 K23_capped_trans_read.bed

68948 B21_nocap_trans_read.bed
48733 K17_nocap_trans_read.bed
56267 K23_nocap_trans_read.bed

Best wishes, 
Szi Kay

**Comment by GenomeRIK** [comment] 2019-08-13 21:16
Hi Szi Kay,

This is definitely very weird. There should be at least the same number of lines in the trans_read.bed file as there are accepted reads in the read.txt file. Typically when there are fewer lines in the trans_read.bed it means the run did not complete. 

From your command line and output file names it looks like you used the same prefix for both the gmap and minimap2 TAMA Collapse runs "-p $1_nocap":
GMAP results:
Number of accepted reads in B21_nocap_read.txt: 418215
Number of accepted reads in K17_nocap_read.txt: 348668
Number of accepted reads in K23_nocap_read.txt: 376519
Minimap results:
Number of accepted reads in B21_nocap_read.txt: 414927
Number of accepted reads in K17_nocap_read.txt: 341157
Number of accepted reads in K23_nocap_read.txt: 374795

And you were outputting the log to a file like this:
&> $1.tama_nocap.log 

Are you sure the run logs did not write to the same file? If you ran the gmap and minimap2 TAMA Collapse runs in the same folder, this would happen. And if you ran the minimap2 one first and then GMAP, then the GMAP log would overwrite the minimap2 log. 

Another way to see what is going on is to check the end of the prefix.bed file for the minimap2 no_cap run. What scaffold is in the last line? If you check the same gene number from the capped run, is it the same scaffold? And is that scaffold not the last scaffold in the capped run?

If this is the case then the run definitely did not complete and you should try running again with a different log output file name. Then check the log output again to see what it says.

Please let me know what you find, because if this is a bug in TAMA Collapse then I would like to fix it. 

Thank you,
Richard

**Comment by GenomeRIK** [comment] 2019-08-13 21:16
Hi Szi Kay,

This is definitely very weird. There should be at least the same number of lines in the trans_read.bed file as there are accepted reads in the read.txt file. Typically when there are fewer lines in the trans_read.bed it means the run did not complete. 

From your command line and output file names it looks like you used the same prefix for both the gmap and minimap2 TAMA Collapse runs "-p $1_nocap":
GMAP results:
Number of accepted reads in B21_nocap_read.txt: 418215
Number of accepted reads in K17_nocap_read.txt: 348668
Number of accepted reads in K23_nocap_read.txt: 376519
Minimap results:
Number of accepted reads in B21_nocap_read.txt: 414927
Number of accepted reads in K17_nocap_read.txt: 341157
Number of accepted reads in K23_nocap_read.txt: 374795

And you were outputting the log to a file like this:
&> $1.tama_nocap.log 

Are you sure the run logs did not write to the same file? If you ran the gmap and minimap2 TAMA Collapse runs in the same folder, this would happen. And if you ran the minimap2 one first and then GMAP, then the GMAP log would overwrite the minimap2 log. 

Another way to see what is going on is to check the end of the prefix.bed file for the minimap2 no_cap run. What scaffold is in the last line? If you check the same gene number from the capped run, is it the same scaffold? And is that scaffold not the last scaffold in the capped run?

If this is the case then the run definitely did not complete and you should try running again with a different log output file name. Then check the log output again to see what it says.

Please let me know what you find, because if this is a bug in TAMA Collapse then I would like to fix it. 

Thank you,
Richard

**Comment by SziKayLeung** [comment] 2019-08-20 11:48
Hello Richard, 

Apologies for the late reply - I reran the three samples again with TAMA collapse and as before in separate folders. The numbers for degradation and reads etc are exactly the same as before,you are right, the run for the minimap no_cap did not complete. 

==> B21.tama_nocap.log <==
invoke add_a_to_b_group m54082_190303_070925/65012266/ccs m54082_190303_070925/36373090/ccs
trans_a already in group, should be nocap trans: m54082_190303_070925/65012266/ccs
invoke add_a_to_b_group m54082_190303_070925/12452031/ccs m54082_190303_070925/36373090/ccs
trans_a already in group, should be nocap trans: m54082_190303_070925/12452031/ccs
invoke add_a_to_b_group m54082_190303_070925/23003536/ccs m54082_190303_070925/36373090/ccs
trans_a already in group, should be nocap trans: m54082_190303_070925/23003536/ccs
truncated transcript
Error with exon end earlier than exon start
121592212       121592212
['m54082_190303_070925/23659313/ccs', 'm54082_190303_070925/11141644/ccs']

==> K17.tama_nocap.log <==
trans_a already in group, should be nocap trans: m54082_190405_063832/42992541/ccs
invoke add_a_to_b_group m54082_190405_063832/18874569/ccs m54082_190405_063832/23986892/ccs
trans_a already in group, should be nocap trans: m54082_190405_063832/18874569/ccs
invoke add_a_to_b_group m54082_190405_063832/42992541/ccs m54082_190405_063832/23986892/ccs
trans_a already in group, should be nocap trans: m54082_190405_063832/42992541/ccs
truncated transcript
truncated transcript
Error with exon end earlier than exon start
121592212       121592212
['m54082_190405_063832/64553110/ccs', 'm54082_190405_063832/18874569/ccs', 'm54082_190405_063832/42992541/ccs']

==> K23.tama_nocap.log <==
more than one best e end! 121600908 num_trans: 5
more than one best e end! 121626503 num_trans: 5
truncated transcript
truncated transcript
truncated transcript
truncated transcript
truncated transcript
Error with exon end earlier than exon start
121592212       121592212
['m54082_190524_145911/42664068/ccs', 'm54082_190524_145911/27132643/ccs']

Thank you for all your help, 
Szi Kay

**Comment by GenomeRIK** [comment] 2019-08-20 12:31
Hi Szi Kay,

Ok so they are all getting hung up on the same gene. 

This is the error:
Error with exon end earlier than exon start
121592212 121592212

Those coordinates are the identified exon start and end for the problematic exon. This happens in a special situation when the transcript models being merged have a wobble pattern that wobble walks over splice junction coordinates. So one model has an exon end which is upstream of a matching model's exon start.

This could be due to problems with SJ mapping or perhaps even some real biological situation.

It's a bit of a complicated thing to describe. If you are curious you can use the pre-collapse models from the trans_read.bed files for the reads shown in the error line and view them in a genome browser. 

If you have trouble doing this I can do it for you if you send me the bed lines for:
['m54082_190303_070925/23659313/ccs', 'm54082_190303_070925/11141644/ccs']
['m54082_190405_063832/64553110/ccs', 'm54082_190405_063832/18874569/ccs', 'm54082_190405_063832/42992541/ccs']
['m54082_190524_145911/42664068/ccs', 'm54082_190524_145911/27132643/ccs']

Anyway, one way to deal with this is to use LDE to filter out reads with high error rate near the splice junctions:
python $TAMA/tama_collapse.py \
-s $1.sorted.sam -f $REFERENCE/mm10.fa -p $1_nocap \
-d merge_dup -x no_cap -a 100 -z 100 -sj sj_priority -sjt 10 -lde 1 &> $1.tama_nocap.log 

This does not guarantee that the situation will not occur again but if this fixes it, then it is very strong evidence that there was a bad read map causing the issue. If you still get the error with these parameters, then you should really look at the models there to see what is going on. This error occurs due to a situation in the data which should be resolved by adjusting parameters. So it is meant to highlight that there are issues in the data and the chosen parameters are not the best. 

Another thing you can do to eliminate this error is run without sj_priority and choose longest exon:
python $TAMA/tama_collapse.py \
-s $1.sorted.sam -f $REFERENCE/mm10.fa -p $1_nocap \
-d merge_dup -x no_cap -a 100 -z 100  -e longest_ends &> $1.tama_nocap.log 

All of this is based on what I think is happening given the error output but it would be best if you could share the bed lines for those reads so I can make sure this is really what the problem is. If you cannot find the bed lines for those reads in the no_cap runs, you will be able to find them in the trans_read.bed files from the capped runs. 

Cheers,
Richard

**Comment by GenomeRIK** [comment] 2019-09-23 11:31
Hi Szi Kay,

It's been a while since your last reply so I am going to assume the issue has been resolved. I am closing this issue thread but if you still need help on this just continue to post on it and I will respond. 

Thank you,
Richard

**Closed by GenomeRIK** 2019-09-23 11:31 UTC
