### ISSUE TITLE
tama_cds_regions_bed_add issue

### ISSUE THREAD

**Issue by emmabailey94** [GenomeRIK/tama#51] opened 2021-03-03 16:35 UTC
Hi,

I've reached the final step of the tama GO pipeline and encountered an error:

```
Traceback (most recent call last):
  File "/tama/tama_go/orf_nmd_predictions/tama_cds_regions_bed_add.py", line 140, in <module>
    block_start_list = line_split[11].split(",")
IndexError: list index out of range
```

The output from the blastp parser in the previous step looks as it should as far as I can tell (I've attached the file: [parser_all.txt](https://github.com/GenomeRIK/tama/files/6077506/parser_all.txt)), and the bed/fasta files I'm using haven't been changed since I've started the pipeline. 

This was my command:
`python2 /tama/tama_go/orf_nmd_predictions/tama_cds_regions_bed_add.py -p parsed_blastp_output -a l_tama_bed_file.bed -f l.fasta -o l_final_tama.bed`

Any help would be appreciated!

Thanks,
Emma

**Comment by GenomeRIK** [comment] 2021-04-20 11:29
Thank you emailing me Emma.

As we went over via email this issue was actually caused by an issue with the mapper. I will close this thread now. 

Cheers,
Richard

**Closed by GenomeRIK** 2021-04-20 11:29 UTC
